from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from faceless_video_machine.models import ResearchSource, VideoProject
from faceless_video_machine.projects import create_project
from faceless_video_machine.research import ResearchBrief, save_research
from faceless_video_machine.script_generation import TemplateProvider, load_script_draft, render_script_markdown, save_script_draft
from faceless_video_machine.script_planning import create_script_plan, save_script_plan


class ScriptGenerationTests(unittest.TestCase):
    def test_template_provider_creates_all_retention_sections(self) -> None:
        brief = ResearchBrief(
            "sample",
            [ResearchSource("https://example.com/fact", "Example source", key_facts=["A sourced fact"], citation="Example 2026")],
            ["A possible angle"],
        )
        plan = create_script_plan("sample", "Sample", "Topic", "Audience")
        draft = TemplateProvider().generate(brief, plan)
        names = {section.name for section in draft.sections}
        self.assertEqual(names, {"Cold open", "Hook", "Context", "Curiosity loops", "Progressive reveals", "Pattern interrupts", "Payoff", "Conclusion", "CTA"})
        self.assertEqual(draft.sourced_facts, ["A sourced fact"])
        self.assertEqual(draft.generated_ideas, ["A possible angle"])
        self.assertIn("Example 2026", render_script_markdown(draft))

    def test_draft_round_trip_and_persistence(self) -> None:
        with tempfile.TemporaryDirectory() as root:
            directory = create_project(VideoProject("sample", "Sample"), root)
            plan = create_script_plan("sample", "Sample", "Topic", "Audience")
            save_script_plan(plan, directory)
            save_research(ResearchBrief("sample"), directory)
            draft = TemplateProvider().generate(ResearchBrief("sample"), plan)
            json_path, markdown_path = save_script_draft(draft, directory)
            self.assertEqual(load_script_draft(directory).to_dict(), json.loads(json_path.read_text()))
            self.assertIn("Generated by the dependency-free TemplateProvider", markdown_path.read_text())


if __name__ == "__main__":
    unittest.main()
