"""Provider-based draft generation using only local, standard-library code."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Protocol

from .research import ResearchBrief
from .script_planning import ScriptPlan


@dataclass(slots=True)
class DraftSection:
    """One structured draft section and the references supporting it."""

    name: str
    content: str
    references: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class ScriptDraft:
    project_id: str
    provider: str
    sections: list[DraftSection] = field(default_factory=list)
    sourced_facts: list[str] = field(default_factory=list)
    generated_ideas: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "project_id": self.project_id,
            "provider": self.provider,
            "sections": [section.to_dict() for section in self.sections],
            "sourced_facts": list(self.sourced_facts),
            "generated_ideas": list(self.generated_ideas),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ScriptDraft":
        return cls(
            project_id=data["project_id"],
            provider=data["provider"],
            sections=[DraftSection(**item) for item in data.get("sections", [])],
            sourced_facts=list(data.get("sourced_facts", [])),
            generated_ideas=list(data.get("generated_ideas", [])),
        )


class ScriptProvider(Protocol):
    """Interface for replaceable local or future free providers."""

    name: str

    def generate(self, brief: ResearchBrief, plan: ScriptPlan) -> ScriptDraft:
        """Create a structured draft from an existing brief and plan."""


class TemplateProvider:
    """A deterministic provider requiring no API key, model, or network service."""

    name = "template"

    def generate(self, brief: ResearchBrief, plan: ScriptPlan) -> ScriptDraft:
        facts: list[str] = []
        references: list[str] = []
        for source in brief.sources:
            reference = source.citation or source.title
            for fact in source.key_facts or []:
                facts.append(fact)
                references.append(f"{reference} — {source.url}")

        fact_block = (
            "Sourced facts to explain:\n" + "\n".join(f"- {fact}" for fact in facts)
            if facts
            else "No sourced facts have been recorded yet. Add sources before asserting factual claims."
        )
        reveal_content = "\n".join(
            f"Beat {index}: {reveal}\n{fact_block if index == len(plan.progressive_reveals) else 'Use only evidence from the research brief for this beat.'}"
            for index, reveal in enumerate(plan.progressive_reveals, 1)
        ) or "No reveal beats were planned."
        loops = "\n".join(f"- {loop}" for loop in plan.curiosity_loops) or "- No loops were planned."
        interrupts = "\n".join(f"- {item}" for item in plan.pattern_interrupts) or "- No pattern interrupts were planned."

        sections = [
            DraftSection("Cold open", plan.cold_open),
            DraftSection("Hook", f"Set up the question: {plan.main_curiosity_question}"),
            DraftSection("Context", f"{plan.context}\n\n{fact_block}", references),
            DraftSection("Curiosity loops", loops),
            DraftSection("Progressive reveals", reveal_content, references),
            DraftSection("Pattern interrupts", interrupts),
            DraftSection("Payoff", f"{plan.payoff}\n\nTie the answer back to: {plan.main_curiosity_question}", references),
            DraftSection("Conclusion", plan.conclusion),
            DraftSection("CTA", plan.call_to_action),
        ]
        return ScriptDraft(
            project_id=plan.project_id,
            provider=self.name,
            sections=sections,
            sourced_facts=facts,
            generated_ideas=list(brief.generated_ideas),
        )


def render_script_markdown(draft: ScriptDraft) -> str:
    lines = [
        f"# Script draft: {draft.project_id}",
        "",
        "> Generated by the dependency-free TemplateProvider. This is a structured draft, not a claim that unsourced ideas are facts.",
        "",
    ]
    for section in draft.sections:
        lines.extend([f"## {section.name}", "", section.content, ""])
        if section.references:
            lines.append("**Sources/references**")
            lines.extend(f"- {reference}" for reference in section.references)
            lines.append("")
    lines.extend(["## Sourced facts used", ""])
    lines.extend(f"- {fact}" for fact in draft.sourced_facts) if draft.sourced_facts else lines.append("No sourced facts used.")
    lines.extend(["", "## Generated ideas (not sourced facts)", ""])
    lines.extend(f"- {idea}" for idea in draft.generated_ideas) if draft.generated_ideas else lines.append("No generated ideas recorded.")
    return "\n".join(lines).rstrip() + "\n"


def save_script_draft(draft: ScriptDraft, project_dir: str | Path) -> tuple[Path, Path]:
    directory = Path(project_dir)
    json_path = directory / "script.json"
    markdown_path = directory / "script.md"
    json_path.write_text(json.dumps(draft.to_dict(), indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(render_script_markdown(draft), encoding="utf-8")
    return json_path, markdown_path


def load_script_draft(project_dir: str | Path) -> ScriptDraft:
    path = Path(project_dir) / "script.json"
    if not path.is_file():
        raise FileNotFoundError(f"Script draft not found: {path}")
    return ScriptDraft.from_dict(json.loads(path.read_text(encoding="utf-8")))
